# Generated by Django 4.2 on 2023-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="title",
            field=models.CharField(help_text="Тип материала", max_length=255),
        ),
    ]
