# Generated by Django 4.2 on 2023-04-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0002_alter_material_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="image",
            field=models.TextField(help_text="Ссылка на изображение"),
        ),
        migrations.AlterField(
            model_name="material",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Цена", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="slug",
            field=models.SlugField(help_text="Слаг материала"),
        ),
    ]
