# Generated by Django 4.2 on 2023-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Тип опций", max_length=255)),
                ("slug", models.SlugField(verbose_name="Слаг материала")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.TextField(verbose_name="Ссылка на изображение")),
            ],
        ),
    ]
