# Generated by Django 4.2 on 2023-04-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="base",
            name="image",
            field=models.TextField(help_text="Ссылка на изображение"),
        ),
        migrations.AlterField(
            model_name="base",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Цена", max_digits=10
            ),
        ),
    ]
