# Generated by Django 4.2 on 2023-04-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("size", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="length",
            field=models.IntegerField(help_text="Длина"),
        ),
        migrations.AlterField(
            model_name="size",
            name="percent_price",
            field=models.IntegerField(help_text="Прибавка к цене в %"),
        ),
        migrations.AlterField(
            model_name="size",
            name="width",
            field=models.IntegerField(help_text="Ширина"),
        ),
    ]
