# Generated by Django 4.2 on 2023-04-04 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="base",
        ),
        migrations.RemoveField(
            model_name="product",
            name="material",
        ),
        migrations.RemoveField(
            model_name="product",
            name="option",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
    ]
