# Generated by Django 4.2 on 2023-04-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_remove_product_base_remove_product_material_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Цена", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(help_text="Наименование товара", max_length=255),
        ),
    ]
